# 全局设置
[global]
https = true # 使用HTTPS协议
process = 4 # 进程数

# 代理设置
[proxy]
enable = true # 开关
pool = "proxy.txt" # 代理池

# 用户设置
[user]
update = true # 自动更新凭据
account = """
# 请在这个区域填写您的账号凭据, 每一条凭据应至少包含下述三种身份校验方式之一的完整键值对.
#     Cookie: bili_jct=...;DedeUserID=...;DedeUserID__ckMd5=...;sid=...;SESSDATA=...;
#      Token: accessToken=...;refreshToken=...;
#   Password: username=...;password=...;
username=22娘;password=GodKnows;
username=33娘;password=GodKnows;
"""

# 获取用户信息
[query]
enable = true # 开关

# 修改隐私设置
[setPrivacy]
enable = false # 开关
showFavourite = false # 展示[我的收藏夹]
showBangumi = false # 展示[订阅番剧]
showTag = false # 展示[订阅标签]
showReward = false # 展示[最近投币的视频]
showInfo = false # 展示[个人资料]
showGame = false # 展示[最近玩过的游戏]

# 银瓜子兑换硬币
[silver2Coins]
enable = true # 开关

# 观看
[watch]
enable = true # 开关
aid = [29278585, 20032006, 14594803] # 稿件av号

# 好评
[like]
enable = true # 开关
aid = [29278585, 20032006, 14594803] # 稿件av号

# 投币
[reward]
enable = true # 开关
aid = [29278585, 20032006, 14594803] # 稿件av号
double = [true, true, true] # 双倍投币

# 收藏
[favour]
enable = true # 开关
aid = [29278585, 20032006, 14594803] # 稿件av号

# 分享
[share]
enable = true # 开关
aid = [29278585, 20032006, 14594803] # 稿件av号

# 关注
[follow]
enable = true # 开关
mid = [124811915] # 被关注用户UID
secret = [true] # 悄悄关注

# 弹幕发送
[danmakuPost]
enable = false # 开关
aid = [25581792] # 稿件av号
message = ["哔哩哔哩 (゜-゜)つロ 干杯~"] # 弹幕内容
moment = [0] # 弹幕发送时间(为-1则随机选择发送时间)

# 评论点赞
[commentLike]
enable = false # 开关
otype = ["article"] # 作品类型(视频video; 活动activity; 相簿gallery; 文章article)
oid = [617468] # 作品ID
rpid = [864171896] # 评论ID

# 评论发表
[commentPost]
enable = false # 开关
otype = ["video"] # 作品类型(视频video; 活动activity; 相簿gallery; 文章article)
oid = [25581792] # 作品ID
message = ["哔哩哔哩 (゜-゜)つロ 干杯~"] # 评论内容
floor = [0] # 目标楼层(为0则直接发表一条评论)
critical = [3] # 临界范围

# 动态点赞
[dynamicLike]
enable = false # 开关
did = [155455735691418008] # 动态ID

# 动态转发
[dynamicRepost]
enable = false # 开关
did = [155455735691418008] # 动态ID
message = ["转发动态"] # 转发内容

# 会员购抢购
[mallRush]
enable = false # 开关
itemID = [10001749] # 商品ID
thread = [2] # 线程数
headless = true # 隐藏窗口
timeout = 10 # 超时刷新

# 会员购周年庆活动签到
[mallSign]
enable = false # 开关

# 会员购周年庆活动扭蛋
[mallLottery]
enable = false # 开关

# 会员购周年庆活动中奖查询
[mallPrize]
enable = false # 开关

# 直播助手
[liveTool]
enable = false # 开关
autoUpdate = true # 自动更新
printDanmaku = false # 显示弹幕
dailySilver2Coins = false # 每日银瓜子兑换硬币
dailyCoins2Silver = false # 每日硬币兑换银瓜子
monitorRoom = 23058 # 监听房间

# 每日自动投币
[liveTool.dailyGiveCoins]
number = 5 # 总投币枚数(为0则关闭该组件)
specialUp = [] # 投给特定Up主(列表为空则随机投给排行榜上的Up主)

# 投满当前佩戴勋章的亲密度
[liveTool.gainIntimacy]
enable = true # 开关
otherRoom = [] # 其余勋章对应房间

# 自动送出即将过期的直播礼物
[liveTool.giveExpiringGifts]
enable = true # 开关
expiringTime = 43200 # 过期倒计时
toMedal = true # 投喂给勋章
toRoom = 5551309 # 投喂给房间
